package io.phasetwo.service.resource;

public enum OrganizationResourceType {
  ORGANIZATION,
  ORGANIZATION_MEMBERSHIP,
  ORGANIZATION_ROLE,
  ORGANIZATION_ROLE_MAPPING,
  TEAM,
  TEAM_MEMBERSHIP,
  ORGANIZATION_POSITION,
  ORGANIZATION_POSITION_ROLE_MAPPING,
  ORGANIZATION_POSITION_USER_MEMBERSHIP,
  ORGANIZATION_POSITION_SUBORDINATE,
  INVITATION;
}
